linters:
  disable-all: true
  enable:
    - goconst
    - godot
    - godox
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - revive
    - typecheck
    - unconvert
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/devpies/reporter
  revive:
    enable-all-rules: true
    rules:
      - name: line-length-limit
        arguments: [ 120 ]
      - name: cognitive-complexity
        arguments: [ 16 ]
      - name: add-constant
        arguments:
          - allowInts: '0,1'
      - name: max-public-structs
        arguments: [ 16 ]
      - name: cyclomatic
        arguments: [ 16 ]

issues:
  include:
    - EXC0012
    - EXC0015

run:
  tests: false