version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - goconst
    - godot
    - godox
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace
  settings:
    gosec:
      excludes:
        - G204
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          arguments:
            - 120
        - name: cognitive-complexity
          disabled: true
        - name: add-constant
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          arguments:
            - 16
        - name: cyclomatic
          disabled: true
        - name: error-strings
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/devpies/reporter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
