name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: 'gomod'   # built-in module cache
          go-version: '1.22.4'
      - name: Install dependencies
        run: |
          make install
          go mod tidy

      - name: Run tests
        run: make test